"""user变更

Revision ID: c2babde07b4e
Revises: c57720e069fd
Create Date: 2026-07-22 17:05:34.995907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2babde07b4e'
down_revision: Union[str, Sequence[str], None] = 'c57720e069fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级管理员'))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
